# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureMysqlDeployment@1
  inputs:
    azureSubscription: 'BFSI_LGI_DevOps_Training_POC(f3f0b402-1498-4537-9728-704a780011a0)'
    ServerName: 'mydemoserver1910.mysql.database.azure.com'
    SqlUsername: 'mydemoadmin@mydemoserver1910'
    SqlPassword: 'Virtualmachine1@'
    TaskNameSelector: 'SqlTaskFile'
    IpDetectionMethod: 'AutoDetect'